spring.application.name=secureapi
spring.datasource.url=jdbc:postgresql://localhost:5432/securedb
spring.datasource.username=risheek
spring.datasource.password=risheek@05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT config
jwt.secret=3f8a2b1c9d4e7f6a5b8c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2
jwt.expiration=86400000